# Generated by Django 5.2.3 on 2025-07-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_qnacomment_author_alter_qnaquestion_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnaquestion',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='qnacomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qnaquestion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qnaquestion',
            name='category',
            field=models.CharField(choices=[('mental_illness', '정신 질환 의심'), ('relationship', '연애 고민'), ('daily_life', '일상 공유'), ('other_advice', '기타 조언 구하기')], max_length=30),
        ),
    ]
