# Generated by Django 5.2.3 on 2025-07-24 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(choices=[('ASCX', 'ASCX'), ('ASCI', 'ASCI'), ('ASOX', 'ASOX'), ('ASOI', 'ASOI'), ('ABCX', 'ABCX'), ('ABCI', 'ABCI'), ('ABOX', 'ABOX'), ('ABOI', 'ABOI'), ('RSCX', 'RSCX'), ('RSCI', 'RSCI'), ('RSOX', 'RSOX'), ('RSOI', 'RSOI'), ('RBCX', 'RBCX'), ('RBCI', 'RBCI'), ('RBOX', 'RBOX'), ('RBOI', 'RBOI')], max_length=8, unique=True)),
                ('type_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('traits', models.TextField()),
                ('problems', models.TextField()),
                ('recommendations', models.TextField()),
                ('character_image', models.ImageField(blank=True, null=True, upload_to='report_characters/')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reporttype')),
            ],
        ),
    ]
